### ISSUE TITLE
Пакет language

### ISSUE THREAD

**Issue by owerworls** [esasby/hgrosh#1]
В общем, ребята, у вас косячек такой: в языковом пакете вы закрываете PHP тег ?>  и после него в русской версии стоит пару пустых пробелов. При загрузке этого пакета в методе `pay()` контроллера ControllerExtensionPaymentHutkiGrosh (`$this->language->load(self::BASE_PATH);`)  эти пару строк выводятся в тело странички, что препятствует срабатыванию http-заголовка с переадресацией. 

Ошибка срабатывает как-то выборочно. На моем хосте она не срабатывает (hostlife.net). На domen.by она штопорит оплату. От чего зависит - не выяснял.

В общем предложение таково: не закрывайте PHP теги в языковых пакетах.

CMS OpenCart 3.0

**Comment by AlyaxeyAskerka** [comment]
Добрый день! 
Спасибо за обнаруженный баг. По Вашему замечанию внесли необходимые правки и обновили файлы.
